### ISSUE TITLE
Vulnerabilities in dependencies

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [sociomantic-tsunami/zoidberg#40]
See https://github.com/sociomantic-tsunami/zoidberg/network/alerts

Please update or if the project is abandoned, let's archive it to make that clear.

**Comment by leandro-lucarella-sociomantic** [comment]
ping @zsolt-nagy-sociomantic maybe you know what should we do with this?

**Comment by zsolt-nagy-sociomantic** [comment]
I am re-routing it to the programmatic team, as it was maintained by the Creatives team before.

**Comment by ido-flaishon-sociomantic** [comment]
@leandro-lucarella-sociomantic I can't access the link, I probably don't have any permissions.

**Comment by leandro-lucarella-sociomantic** [comment]
OK, after some talks and review, this project seems to be abandoned and unused, so we'll just archive it.
